name: CI/CD vinno

on:
  push:
    branches:
      - "**"

jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Welcome message
        run: echo "This is my first GitHub Action job"

      - name: List all files
        run: ls -la

      - name: Read file
        run: cat my-first-ci.yaml
