name: CI/CD vinno

on:
  push:
    branches:
      - "**"

jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Checkout repository manually
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin ${{ github.ref }}
          git checkout ${{ github.sha }}

      - name: Welcome message
        run: echo "This is my first GitHub Action job"

      - name: List all files
        run: ls -la

      - name: Read file
        run: cat README.md
